### ISSUE TITLE
Error running bimmerconnected

### ISSUE THREAD

**Issue by erik73** [m1n3rva/bimmer_connected#61]
I get the following error running this command:

bimmerconnected fingerprint "username" "password" rest_of_world

`DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "POST /webapi/oauth/token HTTP/1.1" 200 None
DEBUG:bimmer_connected.account:got new token "zzzzzzzzzzzzzzzxxxxxxxxxxxxxxxxx" with expiration date 2018-04-03 05:59:33.105577
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 106, in <module>
    main()
  File "/usr/local/bin/bimmerconnected", line 44, in main
    args.func(args)
  File "/usr/local/bin/bimmerconnected", line 72, in fingerprint
    log_responses=time_dir)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 55, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 183, in _get_vehicles
    logfilename='vehicles')
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 129, in send_request
    self._log_response_to_file(response, logfilename)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 137, in _log_response_to_file
    anonymized_data = json.dumps(self._anonymize_data(response.json()), indent=2, sort_keys=True)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in _anonymize_data
    json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in <listcomp>
    json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in _anonymize_data
    json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in <listcomp>
    json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value]
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 161, in _anonymize_data
    for key, value in json_data.items():
AttributeError: 'str' object has no attribute 'items'
`
The vehicle fingerprint folder is created, but it is empty. 
My car is a new BMW i3 LCI 2018. I use the Swedish Connected Drive website.

What is wrong?

**Comment by erik73** [comment]
I tried running the following command: bimmerconnected fingerprint "username" "password" rest_of_world
It gives me a nice json output with all the features of my car. My guess is that the anonymizeing goes wrong when using the fingerprint option.

**Comment by m1n3rva** [comment]
As the line breaks of the log output were messed up, here's the log with proper line breaks:
```
DEBUG:bimmer_connected.account:Getting vehicle list 
DEBUG:bimmer_connected.account:getting new oauth token 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com 
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "POST /webapi/oauth/token HTTP/1.1" 200 None DEBUG:bimmer_connected.account:got new token "zzzzzzzzzzzzzzzxxxxxxxxxxxxxxxxx" with expiration date 2018-04-03 05:59:33.105577 
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one. 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com 
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None Traceback (most recent call last): File "/usr/local/bin/bimmerconnected", line 106, in <module> main() 
File "/usr/local/bin/bimmerconnected", line 44, in main args.func(args) 
File "/usr/local/bin/bimmerconnected", line 72, in fingerprint log_responses=time_dir) 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 55, in __init__ self._get_vehicles() 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 183, in _get_vehicles logfilename='vehicles') 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 129, in send_request self._log_response_to_file(response, logfilename) 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 137, in _log_response_to_file anonymized_data = json.dumps(self._anonymize_data(response.json()), indent=2, sort_keys=True) 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in _anonymize_data json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value] 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in <listcomp> json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value] 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in _anonymize_data json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value] 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 167, in <listcomp> json_data[key] = [ConnectedDriveAccount._anonymize_data(v) for v in value] 
File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 161, in _anonymize_data for key, value in json_data.items(): AttributeError: 'str' object has no attribute 'items'
```

**Comment by m1n3rva** [comment]
@erik73 

Yes, I that was a bug in the anonymizer function. The recursion was not done properly...
Added new test data to prevent this from happening again.

Can you please retry with the current master branch?

**Comment by erik73** [comment]
I downloaded the latest version from the master branch, and it worked perfectly using the fingerprint option.
Thanks for the great work!

**Comment by m1n3rva** [comment]
Great to hear that :smile: --> closing the issue :heavy_check_mark:

**Comment by pmiola73** [comment]
I get the following error running this command:

bimmerconnected fingerprint "username" "password" rest_of_world

DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/authenticate HTTP/1.1" 302 None
Traceback (most recent call last):
  File "/usr/bin/bimmerconnected", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 82, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/bimmer_connected/cli.py", line 112, in fingerprint
    account = ConnectedDriveAccount(args.username, args.password, get_region_from_name(args.region),
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 61, in __init__
    self._get_vehicles()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 226, in _get_vehicles
    self._get_oauth_token()
  File "/usr/lib/python3.8/site-packages/bimmer_connected/account.py", line 126, in _get_oauth_token
    self._oauth_token = response_json['access_token']
KeyError: 'access_token'

Can you please help me?

**Comment by rikroe** [comment]
Is there any difference when you enter `username` and `password` in quotes or without?
Which version of bimmer_connected are you using?
Do you have more than one car in your ConnectedDrive account?

If the problem still exists, please create a new issue, we'll take it from there!

**Comment by gerard33** [comment]
Let's continue in #177.
