### ISSUE TITLE
bmw_connected_drive: Error on device update! 

### ISSUE THREAD

**Issue by plutosherry** [m1n3rva/bimmer_connected#78]
There are error logs at hass 0.74
the bmw states can not be reflash.....

bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 319, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 159, in update
    self._state = not vehicle_state.are_all_cbs_ok
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/state.py", line 224, in are_all_cbs_ok
    for cbs in self.condition_based_services:
TypeError: 'NoneType' object is not iterable

**Comment by m1n3rva** [comment]
this should be fixed with the latest version
