### ISSUE TITLE
Fingerprint function failing

### ISSUE THREAD

**Issue by ipv6freely** [m1n3rva/bimmer_connected#80]
Hi, I'm getting this (obfuscated personal info):
```
cjones@cjones-mbp$ bimmerconnected fingerprint user@domain.com MyP@ssw0rd north_america WBY1234567890
usage: bimmerconnected [-h] {status,fingerprint,lightflash,image} ...
bimmerconnected: error: unrecognized arguments: WBY1234567890


cjones@cjones-mbp$ bimmerconnected fingerprint user@domain.com MyP@ssw0rd north_america
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.us:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.us:443 "POST /webapi/oauth/token HTTP/1.1" 400 None
ERROR:bimmer_connected.account:Unknown status code 400, expected 200
ERROR:bimmer_connected.account:{
  "error" : "invalid_grant",
  "error_description" : "the authN circuit failed"
}
Traceback (most recent call last):
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/bin/bimmerconnected", line 106, in <module>
    main()
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/bin/bimmerconnected", line 44, in main
    args.func(args)
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/bin/bimmerconnected", line 72, in fingerprint
    log_responses=time_dir)
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/lib/python3.6/site-packages/bimmer_connected/account.py", line 55, in __init__
    self._get_vehicles()
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/lib/python3.6/site-packages/bimmer_connected/account.py", line 181, in _get_vehicles
    self._get_oauth_token()
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/lib/python3.6/site-packages/bimmer_connected/account.py", line 88, in _get_oauth_token
    expected_response=200, post=True)
  File "/Users/cjones/.local/share/virtualenvs/python-LG6-DRlH/lib/python3.6/site-packages/bimmer_connected/account.py", line 128, in send_request
    raise IOError(msg)
OSError: Unknown status code 400, expected 200
```

macOS 10.14
Python 3.6.1
bimmer-connected 0.5.1

It's strange that it wouldn't work at all when I provided a VIN, and then if I leave the VIN off I get `invalid_grant`

**Comment by m1n3rva** [comment]
@ipv6freely Thank you for the hint, there the documentation was outdated, you do not need the <vin> argument any more.

BMW seems to have recently changed the urls of their servers. I did fix this for rest_of_world. Can you please try with the latest version and see if this also fixes is for north_america?

**Comment by uchagani** [comment]
@m1n3rva verified that `north_america` is now working.
