### ISSUE TITLE
BMW F22 2015 not working correctly in Hass

### ISSUE THREAD

**Issue by sevenofnine-jni** [m1n3rva/bimmer_connected#82]
I am not getting locks,light, correct location etc in Hass with this component. Running hass 0.77.1

I have attached the status and vehicles files from running fingerprint

I get the following errors in the hass log.

`2018-08-31 08:39:32 ERROR (SyncWorker_4) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (SyncWorker_0) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (SyncWorker_1) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/lock/bmw_connected_drive.py", line 70, in device_state_attributes
    'door_lock_state': vehicle_state.door_lock_state.value
AttributeError: 'NoneType' object has no attribute 'value'
2018-08-31 08:39:32 ERROR (SyncWorker_2) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (SyncWorker_9) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (SyncWorker_3) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [homeassistant.components.binary_sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 251, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 164, in update
    self._state = vehicle_state.has_check_control_messages
  File "/srv/homeassistant/lib/python3.6/site-packages/bimmer_connected/state.py", line 71, in _func_wrapper
    return func(self, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/bimmer_connected/state.py", line 323, in has_check_control_messages
    return len(self.check_control_messages) > 0
TypeError: object of type 'NoneType' has no len()
2018-08-31 08:39:32 ERROR (SyncWorker_5) [bimmer_connected.state] No data available!
2018-08-31 08:39:32 ERROR (MainThread) [homeassistant.components.binary_sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 251, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 162, in update
    self._state = not vehicle_state.are_all_cbs_ok
  File "/srv/homeassistant/lib/python3.6/site-packages/bimmer_connected/state.py", line 224, in are_all_cbs_ok
    for cbs in self.condition_based_services:
TypeError: 'NoneType' object is not iterable
2018-08-31 08:39:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 118, in device_state_attributes
    result['lights_parking'] = vehicle_state.parking_lights.value
AttributeError: 'NoneType' object has no attribute 'value'
2018-08-31 08:39:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 243, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 115, in device_state_attributes
    result['door_lock_state'] = vehicle_state.door_lock_state.value
AttributeError: 'NoneType' object has no attribute 'value'`

[vehicles_0.txt](https://github.com/m1n3rva/bimmer_connected/files/2339337/vehicles_0.txt)
[status_0.txt](https://github.com/m1n3rva/bimmer_connected/files/2339338/status_0.txt)

**Comment by m1n3rva** [comment]
@sevenofnine-jni the server does not return any data (see your status_0.txt), so there is no way to display these attributes for your vehicle. I guess this is related to your `hmiVersion = ID4`.

Concerning the error messages this is something we should fix, see #83.
